### ISSUE TITLE
Failure setting up database

### ISSUE THREAD

**Issue by jsaugustyn** [cmfcmf/AdventureLookup#3]
Hi, I'm getting the following error when I try setting up the database:

An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

**Comment by jsaugustyn** [comment]
OK, solved that problem. I just accepted all the defaults that Composer suggested, which didn't work.

But now, new error, same place:

`[Doctrine\DBAL\Exception\ConnectionException]                              
  An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused`

**Comment by cmfcmf** [comment]
Hey @jsaugustyn,
sorry for the hassle setting up the project! I have updated the installation instructions and the default database parameters (see [here](https://github.com/cmfcmf/AdventureLookup/compare/1ad653af92336b7e1afab643fa872773d8750ba1...master?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)) - I'm currently in the process of doing a fresh clone and going through all the steps one by one again.

Please make sure that in your `app/config/parameters.yml`, the `database_password` and `database_user` are both set to `root` and the `database_name` is set to `adl`. Let me know if it works!

**Comment by jsaugustyn** [comment]
Hey @cmfcmf still no luck. 

Also, there was no `parameters.yml`, though there was a `app/config/parameters.yml.dist.` 

I tried saving it without the .dist extension and then verified that `database_password` and `database_user` were both `root` and `database_name` was `adl`. Everything matched, but still getting the connection refused error. 

Also, got an error in `yarn install --no-bin-links`. Error text as follows:

`warning Error running install script for optional dependency: "/vagrant/node_modules/microtime: Command failed.\nExit code: 1\nCommand: sh\nArguments: -c prebuild-install || node-gyp rebuild\nDirectory: /vagrant/node_modules/microtime\nOutput:\nsh: 1: prebuild-install: not found\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.11.0 | linux | x64\ngyp http GET https://nodejs.org/download/release/v6.11.0/node-v6.11.0-headers.tar.gz\ngyp http 200 https://nodejs.org/download/release/v6.11.0/node-v6.11.0-headers.tar.gz\ngyp http GET https://nodejs.org/download/release/v6.11.0/SHASUMS256.txt\ngyp http 200 https://nodejs.org/download/release/v6.11.0/SHASUMS256.txt\ngyp info spawn /usr/bin/python2\ngyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/vagrant/node_modules/microtime/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/ubuntu/.node-gyp/6.11.0/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/6.11.0',\ngyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/vagrant/node_modules/microtime',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\ngyp ERR! build error \ngyp ERR! stack Error: not found: make\ngyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)\ngyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)\ngyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5\ngyp ERR! stack     at FSReqWrap.oncomDone in 40.68s.`

**Comment by cmfcmf** [comment]
This `yarn install` error can be ignored. 

Can you execute a few things after `vagrant ssh` for me and post the output?
`mysql --version`
`mysql -uroot -proot` (see if login works, type `exit;` to get out of the MySQL console)
`mysql -uroot -proot adl` (see if login into adl database works)

If only the last one fails, type `mysql -uroot -proot -e "CREATE DATABASE adl;"` to manually create the database.

**Comment by jsaugustyn** [comment]
`mysql --version` returns:
`mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper`

`mysql -uroot -proot` returns:
```
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 6
Server version: 5.7.18-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

`mysql -uroot -proot adl` returns:
```
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7
Server version: 5.7.18-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

So, that all looks good! I ran the rest of the install commands with no problem. So it looks like this issue got resolved. However, I'm getting an exception on running the server. I'll close this ticket and open a new one for that issue.
