### ISSUE TITLE
Error running composer

### ISSUE THREAD

**Issue by JohnnyFlash** [cmfcmf/AdventureLookup#4]
When I run 'composer install -n' I get the following error:
```
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DOMDocument" from the global namespace.
  Did you forget a "use" statement? in /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:52
  Stack trace:
  #0 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(263): Symfony\Component\Config\Util\XmlUtils::loadFile('/var/www/new.ad...', Array)
  #1 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/var/www/new.ad...')
  #2 /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(72): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')
  #3 /var/www/new.adventurelookup.com/html/vendor/symfony/symf in /var/www/new.adventurelookup.com/html/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52
```
  .

**Comment by cmfcmf** [comment]
Hey @JohnnyFlash, I think you are missing the `php7.0-xml` package. 

Try running `php bin/symfony_requirements` to see if the system meets all the requirements.

Let me know if it works!

**Comment by JohnnyFlash** [comment]
You are correct.
I was also missing `php7.0-curl`.

On to the next challenge!

**Comment by cmfcmf** [comment]
Alright, closing this then. 👍

**Comment by cmfcmf** [comment]
Ah, @JohnnyFlash, I see you already forked the repo over at https://github.com/AdventureLookup. I think using the GitHub [Transfer Repository](https://help.github.com/articles/about-repository-transfers/) feature is more suited to move it. This way all the issues and metadata are moved as well. I can initiate the transfer into your GitHub organization if you give me permission to create repositories over there. Currently I receive an error when trying to move my repo into the AdventureLookup organization.
> AdventureLookup/AdventureLookup already exists and You don’t have the permission to create repositories on AdventureLookup
