### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by jsaugustyn** [cmfcmf/AdventureLookup#5]
I got through install, but am now getting an exception when I try to run the site.

`php bin/console server:start 0.0.0.0` and `nodejs node_modules/webpack/bin/webpack --watch --progress` both seem to work, but when I navigate to http://localhost:8000/app_dev.php I get the following:

`Warning: SessionHandler::read(): Session data file is not created by your uid`

The stack trace located the problem in `var/cache/dev/classes.php at line 367`

**Comment by jsaugustyn** [comment]
Found the problem. Had to change app/config/config.yml line 30 from:

`save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"`

to:
`save_path: /var/lib/php/sessions`

The app seems to be running!

**Comment by cmfcmf** [comment]
Alright! This might have been caused by a permission problem, maybe try following the [Symfony permission guide](https://symfony.com/doc/current/setup/file_permissions.html#using-acl-on-a-system-that-supports-setfacl-linux-bsd).
